name: Reusable CI (Terraform)
on:
  workflow_call:
    inputs:
      terraform-version: { type: string, default: '1.9.5' }
      working-directory: { type: string, default: '.' }
      run-plan: { type: boolean, default: false }
jobs:
  iac:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with: { terraform_version: ${{ inputs.terraform-version }} }
      - name: fmt
        run: terraform fmt -check -recursive
      - name: init
        run: terraform init -backend=false
      - name: validate
        run: terraform validate
      - name: plan (no backend)
        if: ${{ inputs.run-plan }}
        run: terraform plan -lock=false -input=false -refresh=false
