name: Reusable Container Build (GHCR)
on:
  workflow_call:
    inputs:
      image-name: { type: string, required: true }
      context: { type: string, default: '.' }
      dockerfile: { type: string, default: 'Dockerfile' }
      build-args: { type: string, default: '' } # format: KEY=VAL,KEY2=VAL2
      platforms: { type: string, default: 'linux/amd64' }
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:latest
          provenance: true
          platforms: ${{ inputs.platforms }}
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
